import { Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

const poppins = Poppins({ subsets: ['latin'] , weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],});

export const metadata = {
  title: "ProGrowth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!snap-y !snap-mandatory !scroll-smooth !scroll-pt-[5rem]">
      <body className="bg-zinc-900 text-prowhite  lg:max-w-7xl md:max-w-2xl mx-auto">
        <Nav />
        <div className={poppins.className}>{children}</div>
        <Footer/>
      </body>
    </html>
  );
}
